#!/usr/bin/env php
<?php

use PhpRepos\Console\Infra\Path;
use PhpRepos\Console\Input;
use function PhpRepos\Console\Infra\Filesystem\filename;
use function PhpRepos\Console\Infra\Filesystem\root;
use function PhpRepos\Console\Runner\from_path;
use function PhpRepos\Console\Runner\run;

$entrypoint = filename($_SERVER['SCRIPT_FILENAME']);
$help_text = <<<EOD
Usage: $entrypoint [-h | --help]
               <command> [<options>] [<args>]
EOD;

global $argv;

$help_options = getopt('h', ['help'], $command_index);
// Only care about the first help
$wants_help = (isset($help_options['h']) || isset($help_options['help'])) && $command_index === 2;

$offset = $wants_help ? 2  : 1;

$inputs = Input::make(array_slice($argv, $offset));
$commands_directory = Path::from(root())->sub('Commands');
$command_handlers = from_path($commands_directory);

exit(run($command_handlers, $inputs, $entrypoint, $help_text, $wants_help, $commands_directory));
