#!/usr/bin/env php
<?php

use PhpRepos\Console\Business\Finder;
use PhpRepos\Console\Business\Command;
use PhpRepos\Console\UI;
use PhpRepos\Console\Infra\CLI;
use PhpRepos\Console\Infra\Filesystem;

global $argv;

$entrypoint = 'console';
$short_options = 'h';
$long_options = ['help'];
$options = getopt($short_options, $long_options, $offset);
$wants_help = isset($options['h']) || isset($options['help']);
$inputs = array_slice($argv, $offset);

$root = Filesystem\realpath(__DIR__ . DIRECTORY_SEPARATOR . 'Commands');
$outcome = Finder\path($root, 'Command.php');

if (!$outcome->success) CLI\error($outcome->message) && exit(1);

$command_handlers = $outcome->data['handlers'];

$outcome = Command\find($command_handlers, $inputs);

if (!$outcome->success) {
    if (!$wants_help) CLI\error($outcome->message);

    $outcome = Command\all($command_handlers);
    CLI\write(UI\short_help($outcome->data['commands'], $entrypoint)) && exit($wants_help ? 0 : 1);
}

$command = $outcome->data['name'];
$handler = $outcome->data['handler'];

$outcome = Command\describe($handler);
if (!$outcome->success) CLI\error($outcome->message) && exit(1);

$description = $outcome->data;

if ($wants_help)
    CLI\write(UI\long_help($description, $entrypoint, $command)) && exit(0);

$outcome = Command\run($command, $handler, $command_handlers, $inputs);

if (!$outcome->success)
    CLI\error($outcome->message)
        && CLI\write(UI\long_help($description, $entrypoint, $command))
        && exit($outcome->data['exit_code'] ?? 1);

exit($outcome->data['exit_code'] ?? 0);
